import { verifyMessage, getAddress, computeAddress, isHexString } from 'ethers';

/**
 * Bharat Electronics Limited (BEL) — DID Authentication core (Cloud Functions).
 *
 * PURE cryptographic + policy layer used by the callable Cloud Functions
 * (`verifyDID`, `createChallenge`, `verifySignature`). This module contains
 * NO firebase-admin so the exact same verification logic can be unit-tested
 * headlessly (attack-scenario suite).
 *
 * SECURITY MODEL
 *   • The private key NEVER leaves the employee wallet. Only
 *       { challengeId, DID, walletAddress, signature } reach the backend.
 *   • The verifier trusts ONLY data read from Firestore by the Cloud Function
 *     (challenge document + employee record) and the verified Firebase Auth
 *     context (req.auth.uid / req.auth.token.email). Client-supplied values
 *     are treated as unverified claims and cross-checked.
 *   • Every check must pass or authentication is rejected (fail-closed).
 */

/** Challenge lifetime — short-lived, single-use (per security requirement). */
export const CHALLENGE_TTL_MS = 60 * 1000;

/** Shape of the Firestore `didChallenges/{challengeId}` document. */
export interface ChallengeDoc {
  challenge: string;
  DID: string;
  employeeID: string;
  /** Firebase UID the challenge was issued to (Auth-context binding). */
  uid?: string;
  createdAt: string; // ISO timestamp
  expiresAt: string; // ISO timestamp
  used: boolean;
  walletAddress?: string;
  nonce?: string;
  usedAt?: string;
}

/** Minimal employee fields the verifier relies on (from `employees/{id}`). */
export interface EmployeeDoc {
  employeeId?: string;
  did?: string;
  publicKey?: string;
  role?: string;
  name?: string;
  employeeName?: string;
  email?: string;
  walletAddress?: string;
  walletId?: string;
  status?: string;
  employmentStatus?: string;
  designation?: string;
  department?: string;
}

export interface VerifySignatureInput {
  nowMs: number;
  /** Verified Firebase Auth UID (from the callable function's auth context). */
  authUid: string;
  /** Unverified claims submitted by the client. */
  challengeIdClaim: string;
  didClaim: string;
  walletAddressClaim: string;
  signature: string;
  /** Server data read from Firestore by the Cloud Function. */
  challengeDoc: ChallengeDoc | null;
  employeeDoc: EmployeeDoc | null;
}

export interface VerifyStep {
  label: string;
  passed: boolean;
  detail: string;
}

export interface VerifySignatureResult {
  ok: boolean;
  error?: string;
  steps: VerifyStep[];
  session?: DidSession;
}

export interface DidSession {
  did: string;
  employeeId: string;
  name: string;
  role: string;
  walletAddress: string;
  email?: string;
  designation?: string;
  department?: string;
}

/* ------------------------------ crypto helpers ------------------------------ */

/** Recovers the signer address of an EIP-191 personal_sign signature. */
export function recoverSignerAddress(challenge: string, signature: string): string | null {
  try {
    return verifyMessage(challenge, signature).toLowerCase();
  } catch {
    return null; // malformed signature
  }
}

/** Derives the on-chain address from a stored DID public key (did:ethr style). */
export function addressFromPublicKey(publicKey: string): string | null {
  try {
    return computeAddress(publicKey).toLowerCase();
  } catch {
    return null; // unparseable public key
  }
}

/** True when the challenge expiry instant has passed. */
export function isChallengeExpired(expiresAtIso: string, nowMs: number): boolean {
  const t = Date.parse(expiresAtIso);
  if (Number.isNaN(t)) return true; // unparsable expiry ⇒ treat as expired
  return nowMs > t;
}

/** Parses + normalizes a did:ethr DID. Returns null for any other format. */
export function parseEthrDid(input: string): { did: string; address: string } | null {
  const trimmed = (input || '').trim();
  const m = /^did:ethr:(0x[0-9a-fA-F]{40})$/.exec(trimmed);
  if (!m) return null;
  try {
    const address = getAddress(m[1]); // checksum form
    return { did: `did:ethr:${address}`, address: address.toLowerCase() };
  } catch {
    return null;
  }
}

/* --------------------------- challenge construction -------------------------- */

/** Cryptographically secure nonce is generated by the CALLER (node:crypto). */
export function buildChallengeText(params: {
  did: string;
  walletAddress: string;
  nonce: string;
  issuedAtMs: number;
  expiresAtMs: number;
}): string {
  return [
    'BEL Trust Platform',
    '',
    'Sign this one-time challenge to prove control of your DID.',
    'This challenge is single-use and expires in 60 seconds.',
    '',
    `DID: ${params.did}`,
    `Address: ${params.walletAddress}`,
    `Nonce: ${params.nonce}`,
    `Issued At: ${new Date(params.issuedAtMs).toISOString()}`,
    `Expires At: ${new Date(params.expiresAtMs).toISOString()}`,
  ].join('\n');
}

const INACTIVE_STATUSES = new Set([
  'revoked',
  'suspended',
  'inactive',
  'terminated',
  'disabled',
  'blocked',
]);

/** Account-status gate: employees must be active/verified to authenticate. */
export function isEmployeeActive(employee: EmployeeDoc | null): boolean {
  if (!employee) return false;
  const status = (employee.status || '').trim().toLowerCase();
  if (status && INACTIVE_STATUSES.has(status)) return false;
  const employment = (employee.employmentStatus || '').trim().toLowerCase();
  if (employment && INACTIVE_STATUSES.has(employment)) return false;
  return true;
}

/* --------------------------- server-side evaluation -------------------------- */

/**
 * The FULL server-side verification pipeline (checklist a–h of the security
 * requirements). Runs inside the Cloud Function with data read from Firestore:
 *   a. authenticated Firebase UID matches challenge UID
 *   b. submitted DID matches challenge DID
 *   c. submitted wallet address matches challenge wallet address
 *   d. challenge exists
 *   e. challenge is not expired
 *   f. challenge.used == false
 *   g. signature is cryptographically valid (EIP-191 recovery)
 *   h. signature proves control of the key bound to the registered DID/wallet
 */
export function evaluateSignatureProof(input: VerifySignatureInput): VerifySignatureResult {
  const steps: VerifyStep[] = [];
  const {
    nowMs,
    authUid,
    challengeIdClaim,
    didClaim,
    walletAddressClaim,
    signature,
    challengeDoc,
    employeeDoc,
  } = input;

  const fail = (error: string): VerifySignatureResult => ({ ok: false, error, steps });

  if (!signature) return fail('Missing digital signature.');

  // — d. Challenge exists —
  if (!challengeDoc) {
    return fail(
      `Challenge '${challengeIdClaim}' not found. Restart the sign-in to get a fresh challenge.`
    );
  }
  steps.push({ label: 'Challenge found', passed: true, detail: `didChallenges/${challengeIdClaim}` });

  // — a. UID binding (Firebase Auth context — never a client claim) —
  const challengeUid = (challengeDoc.uid || '').trim();
  if (challengeUid && challengeUid !== authUid) {
    return fail('This challenge was issued to a different authenticated user (UID mismatch).');
  }
  steps.push({ label: 'Firebase UID match', passed: true, detail: `uid ${authUid}` });

  // — f. Single-use (replay protection) —
  if (challengeDoc.used === true) {
    return fail('Challenge has already been used (replay detected). Restart the sign-in.');
  }
  steps.push({ label: 'Challenge single-use', passed: true, detail: 'used = false' });

  // — e. Expiry —
  if (isChallengeExpired(challengeDoc.expiresAt, nowMs)) {
    return fail('Challenge expired. Restart the sign-in to get a fresh challenge.');
  }
  steps.push({ label: 'Challenge unexpired', passed: true, detail: `valid until ${challengeDoc.expiresAt}` });

  // — b. DID claim matches the challenged DID —
  const challengedDid = (challengeDoc.DID || '').trim();
  if (!didClaim || didClaim.trim().toLowerCase() !== challengedDid.toLowerCase()) {
    return fail('Submitted DID does not match the DID this challenge was issued for.');
  }
  steps.push({ label: 'DID match', passed: true, detail: challengedDid });

  // — c. Wallet claim matches the challenged wallet —
  const challengedWallet = (challengeDoc.walletAddress || '').trim().toLowerCase();
  if (challengedWallet && walletAddressClaim.trim().toLowerCase() !== challengedWallet) {
    return fail('Submitted wallet address does not match the wallet bound to this challenge.');
  }
  steps.push({
    label: 'Wallet match',
    passed: true,
    detail: challengedWallet ? `${challengedWallet.substring(0, 10)}…` : 'no wallet binding',
  });

  // — Employee record must exist and be bound to the challenge —
  if (!employeeDoc) {
    return fail(
      `No employee record found in Firebase for '${challengeDoc.employeeID}'. Contact BEL IT Security.`
    );
  }
  const empId = (employeeDoc.employeeId || '').trim();
  if (!empId || empId.toLowerCase() !== (challengeDoc.employeeID || '').trim().toLowerCase()) {
    return fail('Challenge does not belong to the resolved employee record.');
  }
  steps.push({
    label: 'Employee binding',
    passed: true,
    detail: `${empId} · ${employeeDoc.name || employeeDoc.employeeName || employeeDoc.email || ''}`,
  });

  // — DID must be registered to this employee —
  const empDid = (employeeDoc.did || '').trim();
  if (!empDid || empDid.toLowerCase() !== challengedDid.toLowerCase()) {
    return fail('DID is not registered to this employee in the BEL identity registry.');
  }
  steps.push({ label: 'DID ownership', passed: true, detail: 'DID belongs to the authenticated employee' });

  // — Public key exists in Firebase (mandatory) —
  const publicKey = (employeeDoc.publicKey || '').trim();
  if (!publicKey) {
    return fail('No DID public key on file for this employee. Contact BEL IT Security.');
  }
  const pubAddress = addressFromPublicKey(publicKey);
  if (!pubAddress) {
    return fail('Stored DID public key is unparseable. Contact BEL IT Security.');
  }

  // — Account active —
  if (!isEmployeeActive(employeeDoc)) {
    return fail('Employee account is inactive. Access denied — contact BEL IT Security.');
  }
  steps.push({
    label: 'Account status',
    passed: true,
    detail: `${employeeDoc.status || 'Verified'}${employeeDoc.employmentStatus ? ` · ${employeeDoc.employmentStatus}` : ''}`,
  });

  // — g. Cryptographic signature proof —
  const recovered = recoverSignerAddress(challengeDoc.challenge, signature);
  if (!recovered) {
    return fail('Signature malformed — verification failed.');
  }
  // — h. Proves control of the registered DID key AND the bound wallet —
  if (recovered !== pubAddress) {
    return fail('Signature does not verify against the DID public key stored in Firebase.');
  }
  steps.push({
    label: 'Signature verification',
    passed: true,
    detail: `Recovered signer matches DID public key (${pubAddress.substring(0, 10)}…)`,
  });

  const registeredWallet = (employeeDoc.walletAddress || employeeDoc.walletId || '')
    .trim()
    .toLowerCase();
  if (registeredWallet && recovered !== registeredWallet) {
    return fail('Signature does not match the wallet registered to this employee.');
  }
  const boundWallet = (challengeDoc.walletAddress || registeredWallet || '').trim().toLowerCase();
  if (boundWallet && recovered !== boundWallet) {
    return fail('Signature does not match the wallet bound to this challenge.');
  }

  // — Authenticated. Role comes from Firebase (never from the client). —
  const session: DidSession = {
    did: challengedDid,
    employeeId: empId,
    name: employeeDoc.name || employeeDoc.employeeName || empId,
    role: (employeeDoc.role || 'Employee').trim(),
    walletAddress: employeeDoc.walletAddress || boundWallet || pubAddress,
    email: employeeDoc.email,
    designation: (employeeDoc.designation || '').trim() || undefined,
    department: (employeeDoc.department || '').trim() || undefined,
  };

  return { ok: true, steps, session };
}

/**
 * Server-side DID ↔ user binding check used by `verifyDID` and
 * `createChallenge`. The employee record is resolved by the Cloud Function
 * from the verified Firebase Auth context — never from client claims.
 */
export function evaluateDidOwnership(params: {
  did: string;
  employee: EmployeeDoc | null;
}): { ok: boolean; error?: string; walletAddress?: string } {
  const parsed = parseEthrDid(params.did);
  if (!parsed) {
    return { ok: false, error: 'Invalid DID format. Expected did:ethr:0x… (40-digit Ethereum address).' };
  }
  const employee = params.employee;
  if (!employee) {
    return {
      ok: false,
      error: 'No employee record is registered to your Firebase account. Contact BEL IT Security.',
    };
  }
  const empDid = (employee.did || '').trim().toLowerCase();
  if (!empDid) {
    return {
      ok: false,
      error: 'No DID is registered to your employee record yet. Ask BEL IT Security to issue your DID.',
    };
  }
  if (empDid !== parsed.did.toLowerCase()) {
    return { ok: false, error: 'This DID is not registered to the authenticated user. Access denied.' };
  }
  if (!isEmployeeActive(employee)) {
    return { ok: false, error: 'Employee account is inactive. Access denied — contact BEL IT Security.' };
  }
  const walletAddress = (employee.walletAddress || employee.walletId || parsed.address)
    .trim()
    .toLowerCase();
  return { ok: true, walletAddress };
}

/** Validates any DID format accepted by the BEL registry (did:ethr today). */
export function isValidDidFormat(input: string): boolean {
  return parseEthrDid(input) !== null;
}

/** Validates a 40-hex Ethereum address (0x-prefixed), returns checksum form. */
export function toChecksumAddress(input: string): string | null {
  const trimmed = (input || '').trim();
  if (!isHexString(trimmed, 20)) return null;
  try {
    return getAddress(trimmed);
  } catch {
    return null;
  }
}
