-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "did" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "did_public_key" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "did_status" TEXT DEFAULT 'ACTIVE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "did_created_at" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "did_created_by" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "User_did_key" ON "User"("did");
